/**********************************************************************************************************************
 * \file GPT12_Timer_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GPT12_Timer_Interrupt.h"
#include "Ifx_Types.h"
#include "IfxGpt12.h"
#include "IfxPort.h"
#include "Bsp.h"
#include "IfxAsclin_Asc.h"
#include "IfxCpu_Irq.h"
#include "ASCLIN_UART.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <Driver_Can1.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_GPT12_TIMER_T2  10                       /* Define the GPT12 Timer interrupt priority            */
#define ISR_PROVIDER_GPT12_TIMER     IfxSrc_Tos_cpu0         /* Interrupt provider                                   */
#define RELOAD_VALUE                 48828u                  /* Reload value to have an interrupt each 500ms         */
#define RELOAD_VALUE_200ms           19531u
#define RELOAD_VALUE_50ms            4883u
#define RELOAD_VALUE_10ms            977u

#define WAIT_TIME                    1
/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro defining the Interrupt Service Routine */
IFX_INTERRUPT(interruptGpt12_T2, 0, ISR_PRIORITY_GPT12_TIMER_T2);
/* Function to initialize the GPT12 and start the timer */
union
{
    uint16 data;
    uint8 a[2];
} output;

extern int flag;
extern int mode_flag;
int output_data = 0;
void initGpt12Timer(void)
{
    /* GPT12 占쏙옙占� 占십깍옙화 */
    IfxGpt12_enableModule(&MODULE_GPT120); /* GPT12 占쏙옙占� 활占쏙옙화 */
    IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt1BlockPrescaler_16);

    /* Timer T2 占십깍옙화 */
    IfxGpt12_T2_setMode(&MODULE_GPT120, IfxGpt12_Mode_timer);                           /* T2占쏙옙 Timer 占쏙옙占쏙옙 占쏙옙占쏙옙    */
    IfxGpt12_T2_setTimerValue(&MODULE_GPT120, RELOAD_VALUE_200ms);                      /* T2 占쏙옙占싸듸옙 占쏙옙占쏙옙 200占쏙옙占쏙옙 占쏙옙占쏙옙 */

    volatile Ifx_SRC_SRCR *src_t2 = IfxGpt12_T2_getSrc(&MODULE_GPT120);                 /* 占쏙옙占싶뤄옙트 占쌍쇽옙 占쏙옙占쏙옙占쏙옙占쏙옙       */
    IfxSrc_init(src_t2, ISR_PROVIDER_GPT12_TIMER, ISR_PRIORITY_GPT12_TIMER_T2);         /* 占십깍옙화        */
    IfxSrc_enable(src_t2);                                                              /* GPT12 占쏙옙占싶뤄옙트 활占쏙옙화      */

    IfxGpt12_T2_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);                           /* 타占싱몌옙 占쏙옙占쏙옙               */
}

void interruptGpt12_T2(void)
{
    if(flag == 1){
        output_data = receive_ASCLIN_UART_message();
        output.data = output_data;
        if(mode_flag == 1)
        {
            MOTOR_MODE_VEL();
            CAN_TEST_Vel(output.a[0],output.a[1]);
        }
        else
        {
            MOTOR_MODE_POS();
            CAN_TEST_Pos(output.a[0],output.a[1]);
        }
        flag =0;
    }
    /*else{
        input_data = INPUT_control();
        ADC_data = indicateConversionValue();
        send_buff(input_data,ADC_data);
    }*/
}

