/*
 * MotorControl.c
 *
 *  Created on: 2023. 7. 10.
 *      Author: pc_2
 */
/**********************************************************************************************************************
 * \file GPT12_PWM_Capture.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "MotorControl.h"
#include "Ifx_Types.h"
#include "IfxGpt12.h"
#include "Bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_GPT12_TIMER    6                       /* Define the GPT12 Timer interrupt priority            */
#define ISR_PROVIDER_GPT12_TIMER    IfxSrc_Tos_cpu0         /* Interrupt provider                                   */
#define PWM_FREQUENCY               50.0f                   /* Frequency of the PWM signal in Hz                    */

#define GPT1_BLOCK_PRESCALER        32                      /* GPT1 block prescaler value                           */
#define TIMER_T3_INPUT_PRESCALER    32                      /* Timer input prescaler value                          */
#define MAX_VAL_16_BIT              10

#define m_2_pulse                   90
#define vel_2_pulse                 m_2_pulse/50

#define Kp 0.17
#define Ki 0.03
#define Kd 3.0

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
uint32  g_cntOverflow           = 0;    /* Global counter variable for the timer overflow between two edges         */
uint32  g_previousCntVal        = 0;    /* Global variable which stores the timer value of the previous interrupt   */
uint32 timer_cnt = 0;
uint32 timer_count = 0;                 /*g_cntOverflow*/

uint16 dutyUpTime=0;
uint16 dutyDownTime=0;
uint16 g_PWM_DUTY_CYCLE=0;

extern long encoderPos;
int timecnt=0;

float32 fTimer=0;
float64 target=0.8;
float64 target_encoder = 0.0;
float64 error=0.0;
float64 error_d=0.0;
float64 error_s=0.0;
float64 error_old=0.0;
float64 speed = 0;

long en=0;
float64 pwm_output = 0;
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Interrupt Service Routine of timer T2, gets triggered by rising edge on input pin of timer T2 */

int  timeNow(void){
    uint32 currentCntVal = IfxGpt12_T3_getTimerValue(&MODULE_GPT120); /* Get timer value of timer T2 */
    uint32 finalCntVal = 0; /* Variable to calculate final timer counter value */
    finalCntVal = (uint32)(currentCntVal + (MAX_VAL_16_BIT - g_previousCntVal) + ((timer_count - 1) * MAX_VAL_16_BIT));
    g_previousCntVal = currentCntVal;    /* Set g_previousCntVal to currentCntVal for the next calculation */
    return finalCntVal;
}

void setGptPWM_Duty(){
    dutyUpTime = (fTimer * (g_PWM_DUTY_CYCLE / 100.0f)) / PWM_FREQUENCY;
    dutyDownTime = (fTimer * (1 - (g_PWM_DUTY_CYCLE / 100.0f))) / PWM_FREQUENCY;
    IfxGpt12_T2_setTimerValue(&MODULE_GPT120, dutyDownTime);
    IfxGpt12_T4_setTimerValue(&MODULE_GPT120, dutyUpTime);
}

void MOTOR_CONTROL (float64 pwm){
    speed = (pwm / 255) * 100;
    if(speed < 0){
        IfxPort_setPinState(DIR_A_PIN, IfxPort_State_low);
        IfxPort_setPinState(DIR_A_PIN1, IfxPort_State_high);
        g_PWM_DUTY_CYCLE = -speed;
    }
    else{
        IfxPort_setPinState(DIR_A_PIN, IfxPort_State_high);
        IfxPort_setPinState(DIR_A_PIN1, IfxPort_State_low);
        g_PWM_DUTY_CYCLE = speed;
    }
    setGptPWM_Duty();
}

void PID_SPEED_CONTROL(void)
{
    target_encoder += target * vel_2_pulse;
    error = target_encoder - encoderPos;
    error_s += error;
    error_d = error - error_old;

    error_s = (error_s >= 50)  ?  50 : error_s;
    error_s = (error_s <= -50) ? -50 : error_s;

    pwm_output = Kp*error + Kd*error_d + Ki*error_s;

    pwm_output = (pwm_output >= 70)  ?  70 : pwm_output;
    pwm_output = (pwm_output <= 4 && pwm_output > 0)  ?  4 : pwm_output;
    pwm_output = (pwm_output <= -70) ? -70 : pwm_output;
    pwm_output = (pwm_output >= -4 && pwm_output < 0)  ?  -4 : pwm_output;

    if (fabs(error) <= 2)
    {

        MOTOR_CONTROL(0);
        error = 0;
        target = 0;
       // encoderPos = 0;
    }
    else
    {
        MOTOR_CONTROL(pwm_output);
    }
    error_old = error;
}
/* Macro to define the Interrupt Service Routine. */
IFX_INTERRUPT(GPT12_T3_Int0_Handler, 0, ISR_PRIORITY_GPT12_TIMER);

/* Interrupt Service Routine of timer T3, gets triggered after T3 timer overflow */
uint16 cnt10ms=0;
void GPT12_T3_Int0_Handler(void)
{
    //target_encoder += target * vel_2_pulse;
    PID_SPEED_CONTROL();
    IfxPort_togglePin(PWM_A_PIN);
    timer_cnt++;
    if(timer_cnt%2 == 0 && timer_cnt != 0 )
    {
        timer_count++;
        timer_cnt=0;
    }
}

/* This function initializes timer T2 and T3 of the block GPT1 of module GPT12 to capture PWM signals. */
void init_GPT12_module(void)
{
    /* Enable the GPT12 module */
    IfxGpt12_enableModule(&MODULE_GPT120);
    /* Set GPT1 block prescaler to divide the module frequency */
    IfxGpt12_setGpt1BlockPrescaler(&MODULE_GPT120, IfxGpt12_Gpt1BlockPrescaler_32);
    /* Set the GPT12 timer T3 in timer mode */
    IfxGpt12_T3_setMode(&MODULE_GPT120, IfxGpt12_Mode_timer);
    /* Set the Timer T3 direction   */
    IfxGpt12_T3_setTimerDirection(&MODULE_GPT120, IfxGpt12_TimerDirection_down);
    /* Set timer T3 input prescaler to divide the timer frequency */
    IfxGpt12_T3_setTimerPrescaler(&MODULE_GPT120, IfxGpt12_TimerInputPrescaler_32);

    /* Calculate dutyUpTime and dutyDownTime for reloading timer T3 */
    float32 moduleFreq = IfxGpt12_getModuleFrequency(&MODULE_GPT120);
    fTimer = (moduleFreq / (GPT1_BLOCK_PRESCALER * TIMER_T3_INPUT_PRESCALER));
    dutyUpTime = (fTimer * (g_PWM_DUTY_CYCLE / 100.0f)) / PWM_FREQUENCY;
    dutyDownTime = (fTimer * (1 - (g_PWM_DUTY_CYCLE / 100.0f))) / PWM_FREQUENCY;

    /* Set timer T3 value */
    IfxGpt12_T3_setTimerValue(&MODULE_GPT120, dutyDownTime);

    /* Timer T2: reloads the value dutyDownTime in timer T3 */
    /* Set the timer T2 in reload mode */
    IfxGpt12_T2_setMode(&MODULE_GPT120, IfxGpt12_Mode_reload);
    /* Set the T2 input parameter: Negative transition (falling edge) of T3 toggle latch T3OTL */
    IfxGpt12_T2_setReloadInputMode(&MODULE_GPT120, IfxGpt12_ReloadInputMode_fallingEdgeTxOTL);
    /* Set timer T2 value (the value that is reloaded in T3 on negative transition) */
    IfxGpt12_T2_setTimerValue(&MODULE_GPT120, dutyDownTime);

    /* Timer T4: reloads the value dutyUpTime in timer T3 */
    /* Set timer T4 in reload mode */
    IfxGpt12_T4_setMode(&MODULE_GPT120, IfxGpt12_Mode_reload);
    /* Set the T4 input parameter: Positive transition (rising edge) of T3 toggle latch T3OTL */
    IfxGpt12_T4_setReloadInputMode(&MODULE_GPT120, IfxGpt12_ReloadInputMode_risingEdgeTxOTL);
    /* Set timer T4 value (the value that is reloaded in T3 on positive transition) */
    IfxGpt12_T4_setTimerValue(&MODULE_GPT120, dutyUpTime);

    /* Configure the GPT12 interrupt */
    volatile Ifx_SRC_SRCR *src = IfxGpt12_T3_getSrc(&MODULE_GPT120);            /* Get interrupt address            */
    IfxSrc_init(src, ISR_PROVIDER_GPT12_TIMER, ISR_PRIORITY_GPT12_TIMER);       /* Initialize the service request   */
    IfxSrc_enable(src);                                                         /* Enable GPT12 interrupt           */

    IfxPort_setPinModeOutput(PWM_A_PIN, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(DIR_A_PIN, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(DIR_A_PIN1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinState(PWM_A_PIN, IfxPort_State_low);
    IfxPort_setPinState(DIR_A_PIN , IfxPort_State_low);//low�쟾吏� high �썑吏�
    IfxPort_setPinState(DIR_A_PIN1 , IfxPort_State_low);//low�쟾吏� high �썑吏�
}
void runGpt12PWM(void)
{
    IfxGpt12_T3_run(&MODULE_GPT120, IfxGpt12_TimerRun_start);                   /* Start the timer T3               */
}
